name: Infra Deploy

on:
  workflow_dispatch:
    inputs:
      TF_ACTION:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - "plan"
          - "apply"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: |
          cd infra
          terraform init

      - name: Run Terraform Plan
        if: ${{ github.event.inputs.TF_ACTION == 'plan' }}
        run: |
          cd infra
          terraform plan

      - name: Run Terraform Apply
        if: ${{ github.event.inputs.TF_ACTION == 'apply' }}
        run: |
          cd infra
          terraform apply -auto-approve
